modLoader="javafml"
loaderVersion="[20,)"
license="MIT"

[[mods]]
modId="technetium_origins"
displayName="Technetium Origins"
version="1.0.13"
description='''
rework for automaton from origins++
'''
[[dependencies.technetium_origins]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.0,1.20.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.technetium_origins]]
    modId="origins"
    mandatory=true
    versionRange="[0.1.0,)"
    ordering="NONE"
    side="BOTH"
